name: Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⬢ Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Generate changelog and create release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
